# This is a basic workflow to help you get started with Actions

name: Create a Release

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    # The type of runner that the job will run on
    name: "Tagged Pre Release"
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: shasum python script
        run: shasum -a 256 src/cli/soos.py > src/cli/soos.py.sha256
      - name: shasum requirements
        run: shasum -a 256 src/cli/requirements.txt > src/cli/requirements.txt.sha256
      # Runs a single command using the runners shell
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
          files: |
            src/cli/requirements.txt
            src/cli/requirements.txt.sha256
            src/cli/soos.py
            src/cli/soos.py.sha256
