# This is a basic workflow to help you get started with Actions

name: Create a Release

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    # The type of runner that the job will run on
    name: "Tagged Pre Release"
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run Integration Tests
        run: |
          cd tests
          python -m unittest tests.py
          cd ..
        env:
          SOOS_CLIENT_ID: ${{ secrets.SOOS_CLIENT_ID }}
          SOOS_API_KEY: ${{ secrets.SOOS_API_KEY }}
          SOOS_GITHUB_PAT: ${{ secrets.SOOS_GITHUB_PAT }}
      - name: shasum python script
        run: shasum -a 256 src/cli/soos.py > src/cli/soos.sha256
      - name: shasum requirements
        run: shasum -a 256 src/cli/requirements.txt > src/cli/requirements.sha256
      # Runs a single command using the runners shell
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
          files: |
            src/cli/requirements.txt
            src/cli/requirements.sha256
            src/cli/soos.py
            src/cli/soos.sha256